### ISSUE TITLE
Feature: Localization

### ISSUE THREAD

**Issue by DmitryGolubenkov** [DmitryGolubenkov/SharpDockerizer#1]
## Description

We should be able to translate SharpDockerizer to different languages and allow users to choose language they prefer.
Everything must be crossplatform.

## TODO: 

- [x] Add localization support to application
- [x] Add language auto detect feature (should detect user system language on first launch)
- [ ] Add a control to choose application language
- [x] Save chosen language somewhere
- [x] Load chosen language at startup
