### ISSUE TITLE
Feature: Dockerfile templates

### ISSUE THREAD

**Issue by DmitryGolubenkov** [DmitryGolubenkov/SharpDockerizer#17]
# Description
Generated file is currently hardcoded, so users who want to utilize SharpDockerizer will have to modify every file that the app generates is they want to add customizations. I think that the app should support templates - files that can be read by SharpDockerizer and then filled using solution data. This will require some refactoring to achieve, but this is possible. 

# TODO: 

- [x] Refactor app so one generator implementation is not mandatory; also extract helper functions to utilities so they can be utilized by other generators
- [x] Decide how template should look and where it should be stored
- [x] Implement new generator
- [x] Allow to choose between standart generator and templated.

**Comment by DmitryGolubenkov** [comment]
Decided that one generator is more than enough. Refactored default generator to support templates and use only them. Refactoring was made earlier.
The code is still not perfect, but the mandatory part is implemented.
