### ISSUE TITLE
Feature: Recent solutions

### ISSUE THREAD

**Issue by DmitryGolubenkov** [DmitryGolubenkov/SharpDockerizer#2]
## Description
User should be able to quickly open recently opened solution using `File -> Open Recent -> ... ` menu. 

## TODO

- [x] Store recently opened solutions somewhere
- [x] Load recently opened solutions (this should be refreshed at runtime when a new solution is opened. No duplicates!)
- [x] Add a dropdown menu (something like Visual Studio menu) to `File` menu in `TopBar`, that can display loaded list of solutions. (Also refreshed at runtime)
- [x] Load clicked solution into application
- [x] Sort recently opened solutions so that the most recent solution is always on top
