### ISSUE TITLE
Feature: Export Dockerfile

### ISSUE THREAD

**Issue by DmitryGolubenkov** [DmitryGolubenkov/SharpDockerizer#8]
# Description
User should be able to export Dockerfile using several actions:

- Copy to clipboard: as stated
- Export Dockerfile to project folder: as stated. Should ask if user wants to overwrite existing Dockerfile if it exists
- Export Dockerfile to custom folder: opens Save to dialog at least on Windows. Not sure about Linux and MacOS - needs research.

# TODO:

- [x] Create control that will hold three buttons for these operations
- [x] Implement Copy to clipboard
- [x] Implement Export Dockerfile to project folder
- [x] Implement Export Dockerfile to custom folder

**Comment by DmitryGolubenkov** [comment]
Notifications and dialogs still need to be implemented. Couldn't find a way to properly do it for now.
