### ISSUE TITLE
Feature: Refresh solution

### ISSUE THREAD

**Issue by DmitryGolubenkov** [DmitryGolubenkov/SharpDockerizer#9]
# Description
If SharpDockerizer is opened while user works with source code, .NET solution can be changed: projects added, moved or removed, references modified. This can (and will!) break SharpDockerizer. 
We need to implement solution refresh feature. It will allow user to refresh the solution without reopening it.

# TODO: 

- [x] Implement Solution Refresh in `AppLayer`
- [x] Add 'Refresh' button to Solution Viewer
- [x] Auto call Solution Refresh before generating Dockerfile (In `DockerfileGenerator`, I think. Maybe on UI Layer, but I don't think that's a good idea)
- [x] Handle solution refresh in application

**Comment by DmitryGolubenkov** [comment]
Fixed in 06710b423bc67cc73bb789ff21a90f83d4634f18
